//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Measurement.LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FlowResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlowResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Measurement.LocalResources.FlowResource", typeof(FlowResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г/час.
        /// </summary>
        public static string g_hour {
            get {
                return ResourceManager.GetString("g_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г/мин.
        /// </summary>
        public static string g_min {
            get {
                return ResourceManager.GetString("g_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г/сек.
        /// </summary>
        public static string g_sec {
            get {
                return ResourceManager.GetString("g_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г/сутки.
        /// </summary>
        public static string g_sutki {
            get {
                return ResourceManager.GetString("g_sutki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кг/час.
        /// </summary>
        public static string kg_hour {
            get {
                return ResourceManager.GetString("kg_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кг/мин.
        /// </summary>
        public static string kg_min {
            get {
                return ResourceManager.GetString("kg_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кг/сек.
        /// </summary>
        public static string kg_sec {
            get {
                return ResourceManager.GetString("kg_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кг/сутки.
        /// </summary>
        public static string kg_sutki {
            get {
                return ResourceManager.GetString("kg_sutki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на л/час.
        /// </summary>
        public static string l_hour {
            get {
                return ResourceManager.GetString("l_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на л/мин.
        /// </summary>
        public static string l_min {
            get {
                return ResourceManager.GetString("l_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на л/сек.
        /// </summary>
        public static string l_sec {
            get {
                return ResourceManager.GetString("l_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на л/сутки.
        /// </summary>
        public static string l_sutki {
            get {
                return ResourceManager.GetString("l_sutki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м3/час.
        /// </summary>
        public static string m3_hour {
            get {
                return ResourceManager.GetString("m3_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м3/мин.
        /// </summary>
        public static string m3_min {
            get {
                return ResourceManager.GetString("m3_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м3/сек.
        /// </summary>
        public static string m3_sec {
            get {
                return ResourceManager.GetString("m3_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м3/сутки.
        /// </summary>
        public static string m3_sutki {
            get {
                return ResourceManager.GetString("m3_sutki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мг/час.
        /// </summary>
        public static string mg_hour {
            get {
                return ResourceManager.GetString("mg_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мг/мин.
        /// </summary>
        public static string mg_min {
            get {
                return ResourceManager.GetString("mg_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мг/сек.
        /// </summary>
        public static string mg_sec {
            get {
                return ResourceManager.GetString("mg_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мг/сутки.
        /// </summary>
        public static string mg_sutki {
            get {
                return ResourceManager.GetString("mg_sutki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мл3/час.
        /// </summary>
        public static string ml_hour {
            get {
                return ResourceManager.GetString("ml_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мл3/мин.
        /// </summary>
        public static string ml_min {
            get {
                return ResourceManager.GetString("ml_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мл3/сек.
        /// </summary>
        public static string ml_sec {
            get {
                return ResourceManager.GetString("ml_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мл3/сутки.
        /// </summary>
        public static string ml_sutki {
            get {
                return ResourceManager.GetString("ml_sutki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мм3/час.
        /// </summary>
        public static string mm3_hour {
            get {
                return ResourceManager.GetString("mm3_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мм3/мин.
        /// </summary>
        public static string mm3_min {
            get {
                return ResourceManager.GetString("mm3_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мм3/сек.
        /// </summary>
        public static string mm3_sec {
            get {
                return ResourceManager.GetString("mm3_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мм3/сутки.
        /// </summary>
        public static string mm3_sutki {
            get {
                return ResourceManager.GetString("mm3_sutki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -.
        /// </summary>
        public static string not {
            get {
                return ResourceManager.GetString("not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на см3/час.
        /// </summary>
        public static string sm3_hour {
            get {
                return ResourceManager.GetString("sm3_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на см3/мин.
        /// </summary>
        public static string sm3_min {
            get {
                return ResourceManager.GetString("sm3_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на см3/сек.
        /// </summary>
        public static string sm3_sec {
            get {
                return ResourceManager.GetString("sm3_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на см3/сутки.
        /// </summary>
        public static string sm3_sutki {
            get {
                return ResourceManager.GetString("sm3_sutki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на т/час.
        /// </summary>
        public static string ton_hour {
            get {
                return ResourceManager.GetString("ton_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на т/мин.
        /// </summary>
        public static string ton_min {
            get {
                return ResourceManager.GetString("ton_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на т/сек.
        /// </summary>
        public static string ton_sec {
            get {
                return ResourceManager.GetString("ton_sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на т/сутки.
        /// </summary>
        public static string ton_sutki {
            get {
                return ResourceManager.GetString("ton_sutki", resourceCulture);
            }
        }
    }
}
