//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Measurement.LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PressureResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PressureResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Measurement.LocalResources.PressureResource", typeof(PressureResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ат.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на атм.
        /// </summary>
        public static string atm {
            get {
                return ResourceManager.GetString("atm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на аПа.
        /// </summary>
        public static string attoPa {
            get {
                return ResourceManager.GetString("attoPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бар.
        /// </summary>
        public static string bar {
            get {
                return ResourceManager.GetString("bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дПа.
        /// </summary>
        public static string deciPa {
            get {
                return ResourceManager.GetString("deciPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на даПа.
        /// </summary>
        public static string dekaPa {
            get {
                return ResourceManager.GetString("dekaPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЭПа.
        /// </summary>
        public static string EksaPa {
            get {
                return ResourceManager.GetString("EksaPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на фПа.
        /// </summary>
        public static string femtoPa {
            get {
                return ResourceManager.GetString("femtoPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г/м2.
        /// </summary>
        public static string g_m2 {
            get {
                return ResourceManager.GetString("g_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г/мм2.
        /// </summary>
        public static string g_mm2 {
            get {
                return ResourceManager.GetString("g_mm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г/см2.
        /// </summary>
        public static string g_sm2 {
            get {
                return ResourceManager.GetString("g_sm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на гПа.
        /// </summary>
        public static string gektoPa {
            get {
                return ResourceManager.GetString("gektoPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГПа.
        /// </summary>
        public static string GigaPa {
            get {
                return ResourceManager.GetString("GigaPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на гс/м2.
        /// </summary>
        public static string gs_m2 {
            get {
                return ResourceManager.GetString("gs_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на гс/мм2.
        /// </summary>
        public static string gs_mm2 {
            get {
                return ResourceManager.GetString("gs_mm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на гс/см2.
        /// </summary>
        public static string gs_sm2 {
            get {
                return ResourceManager.GetString("gs_sm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на H/м2.
        /// </summary>
        public static string H_m2 {
            get {
                return ResourceManager.GetString("H_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на H/мм2.
        /// </summary>
        public static string H_mm2 {
            get {
                return ResourceManager.GetString("H_mm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на H/см2.
        /// </summary>
        public static string H_sm2 {
            get {
                return ResourceManager.GetString("H_sm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кг/м2.
        /// </summary>
        public static string kg_m2 {
            get {
                return ResourceManager.GetString("kg_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кг/мм2.
        /// </summary>
        public static string kg_mm2 {
            get {
                return ResourceManager.GetString("kg_mm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кг/см2.
        /// </summary>
        public static string kg_sm2 {
            get {
                return ResourceManager.GetString("kg_sm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кгс/м2.
        /// </summary>
        public static string kgs_m2 {
            get {
                return ResourceManager.GetString("kgs_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кгс/мм2.
        /// </summary>
        public static string kgs_mm2 {
            get {
                return ResourceManager.GetString("kgs_mm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кгс/см2.
        /// </summary>
        public static string kgs_sm2 {
            get {
                return ResourceManager.GetString("kgs_sm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KH/м2.
        /// </summary>
        public static string KH_m2 {
            get {
                return ResourceManager.GetString("KH_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KH/мм2.
        /// </summary>
        public static string KH_mm2 {
            get {
                return ResourceManager.GetString("KH_mm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KH/см2.
        /// </summary>
        public static string KH_sm2 {
            get {
                return ResourceManager.GetString("KH_sm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кПа.
        /// </summary>
        public static string kiloPa {
            get {
                return ResourceManager.GetString("kiloPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мвод.ст.
        /// </summary>
        public static string m_H2O {
            get {
                return ResourceManager.GetString("m_H2O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мрт.ст..
        /// </summary>
        public static string m_Hg {
            get {
                return ResourceManager.GetString("m_Hg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мБар.
        /// </summary>
        public static string mBar {
            get {
                return ResourceManager.GetString("mBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МПа.
        /// </summary>
        public static string MegaPa {
            get {
                return ResourceManager.GetString("MegaPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MH/м2.
        /// </summary>
        public static string MH_m2 {
            get {
                return ResourceManager.GetString("MH_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MH/мм2.
        /// </summary>
        public static string MH_mm2 {
            get {
                return ResourceManager.GetString("MH_mm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MH/см2.
        /// </summary>
        public static string MH_sm2 {
            get {
                return ResourceManager.GetString("MH_sm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мкПа.
        /// </summary>
        public static string mikroPa {
            get {
                return ResourceManager.GetString("mikroPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мПа.
        /// </summary>
        public static string miliPa {
            get {
                return ResourceManager.GetString("miliPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ммвод.ст..
        /// </summary>
        public static string mm_H2O {
            get {
                return ResourceManager.GetString("mm_H2O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ммрт.ст..
        /// </summary>
        public static string mm_Hg {
            get {
                return ResourceManager.GetString("mm_Hg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нПа.
        /// </summary>
        public static string nanoPa {
            get {
                return ResourceManager.GetString("nanoPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -.
        /// </summary>
        public static string not {
            get {
                return ResourceManager.GetString("not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Па.
        /// </summary>
        public static string Pa {
            get {
                return ResourceManager.GetString("Pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ППа.
        /// </summary>
        public static string PetaPa {
            get {
                return ResourceManager.GetString("PetaPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пПа.
        /// </summary>
        public static string pikoPa {
            get {
                return ResourceManager.GetString("pikoPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сПа.
        /// </summary>
        public static string santiPa {
            get {
                return ResourceManager.GetString("santiPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на смвод.ст..
        /// </summary>
        public static string sm_H2O {
            get {
                return ResourceManager.GetString("sm_H2O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на смрт.ст..
        /// </summary>
        public static string sm_Hg {
            get {
                return ResourceManager.GetString("sm_Hg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на т/м2.
        /// </summary>
        public static string t_m2 {
            get {
                return ResourceManager.GetString("t_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на т/мм2.
        /// </summary>
        public static string t_mm2 {
            get {
                return ResourceManager.GetString("t_mm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на т/см2.
        /// </summary>
        public static string t_sm2 {
            get {
                return ResourceManager.GetString("t_sm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТПа.
        /// </summary>
        public static string TeraPa {
            get {
                return ResourceManager.GetString("TeraPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на тс/м2.
        /// </summary>
        public static string ts_m2 {
            get {
                return ResourceManager.GetString("ts_m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на тс/мм2.
        /// </summary>
        public static string ts_mm2 {
            get {
                return ResourceManager.GetString("ts_mm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на тс/см2.
        /// </summary>
        public static string ts_sm2 {
            get {
                return ResourceManager.GetString("ts_sm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на иПа.
        /// </summary>
        public static string yoktoPa {
            get {
                return ResourceManager.GetString("yoktoPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИПа.
        /// </summary>
        public static string YottaPa {
            get {
                return ResourceManager.GetString("YottaPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на зПа.
        /// </summary>
        public static string zeptoPa {
            get {
                return ResourceManager.GetString("zeptoPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗПа.
        /// </summary>
        public static string ZettaPa {
            get {
                return ResourceManager.GetString("ZettaPa", resourceCulture);
            }
        }
    }
}
